### ISSUE TITLE
[compiler] move runtime validations to compile-time when we introduce second-pass compilation

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1297]
Some of the validations that happen during runtime can be moved to compile-time once we implement second-pass compilation.

**Comment by nolanlawson** [comment]
Just dug up this issue due to a bug report… This bug can have some serious implications.

Essentially, for any property passed to a component that is _not_ defined in `HTMLElement`/`Element`, you get this error in dev mode:

https://github.com/salesforce/lwc/blob/e8b2c67f45d9e5f4514d39826139f88643741cc2/packages/%40lwc/engine-dom/src/renderer.ts#L219-L228

Unfortunately this error is runtime-dependent. So for instance, if you try to pass `part` to an element:

```html
<x-component part="foo"></x-component>
```

Then this will error in Jest/JSDOM, because `part` is not supported: https://github.com/jsdom/jsdom/issues/3366

Similarly, if [you try to set `inert`](https://github.com/nolanlawson/lwc-barebone/commit/b9b654b5471cee550715f89ca73be5acc2176893), you get an error in Chrome but not Safari Technology Preview (see relevant [browser support for `inert`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert#browser_compatibility)):

![Screen Shot 2022-05-06 at 12 30 48 PM](https://user-images.githubusercontent.com/283842/167206664-684112ef-23c9-40ff-937f-3535e9b8c18b.png)

I think at the very least, we may want to consider making this a warning rather than an error. It seems potentially problematic to have errors thrown in some browsers but not others (even in dev mode).

**Comment by nolanlawson** [comment]
Worth noting: authors can currently use a workaround like:

```js
HTMLElement.prototype.part = null;
```

This works in Jest/JSDOM tests, but it wouldn't work on-platform in the browser, however. (Locker would block it.)

**Comment by nolanlawson** [comment]
Second-pass compilation is not currently planned, and with #3434, all remaining references to this issue are removed from the codebase. I think this issue can be closed for now.
