### ISSUE TITLE
Make lightning-datatable column size responsive?

### ISSUE THREAD

**Issue by az-oolloow** [salesforce/lwc#1356]
I have a LWC component (NOT Aura) that has a datatable with just one column.

By default, the width of that column is 1000 px, which is way too small.

Using `max-column-width="4000"` or similar on the `lightning-datatable` tag i can get the column to size itself to screen width.

However, if the user then resizes the screen, the column does not follow that.

Is there any way to set the column to be 100% width rather than a fixed value in pixels?

**Comment by caridy** [comment]
This question is about lightning global components, which will be in another repo in the future, and you can use other channels for this type of questions. cc @reiniergs who implemented most of the features of the lightning-datatable.

**Comment by ipavlic** [comment]
@caridy At the moment, where are lightning global components? Are they in this repo? What other channels are you advertising in this repo? The only one I could find is Salesforce stackexchange. In effect you are saying: "ask someone else, because we do not support our product".

**Comment by caridy** [comment]
@ipavlic this repo contains the LWC library (which includes the engine, compiler, some dev-tools, etc). It is intended to be used by LWC Authors who want to create components, this repo does not contain a single component. Components are created by other folks, whether those are salesforce employees or not, it does not matter.

Yes, I agree with you that there is a disconnect here, and that we should have a more direct link to things that are related to the set of Lightning Web Components provided out of the box by salesforce, those that were recently open via another repo (https://github.com/salesforce/base-components-recipes), which is own by a different group/team. I suspect that there are ways to get support for individual components, but I don't know the details at the moment. Let me ping some folks that might know better since they work directly on that project. cc @garazi @Gr8Gatsby
