### ISSUE TITLE
Summer 19 release - production - unable to import own custom components in a managed package

### ISSUE THREAD

**Issue by az-oolloow** [salesforce/lwc#1359]
This seems to only affect orgs that are developing managed packages. 

What happens is if you have one **custom** component import another custom component, the js can't compile as it can't find the module (for whatever reason now?)

To replicate this, do the following in Summer 19:

1) Create the first component (e.g. here called TestCo)

Html

```
<template>
Hello world!
</template>
```

Js

```
import { LightningElement } from 'lwc';

export default class TestCo extends LightningElement {}
```

Metadata

```
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata" fqn="testCo">
<apiVersion>45.0</apiVersion>
<isExposed>false</isExposed>
</LightningComponentBundle>
```

2) Create the second component (here called DummyEditor)

Html

```
<template>
<c-test-co></c-test-co>
</template>
```

Js

```
import { LightningElement, api, wire, track } from "lwc";
import { TestCo } from 'c/testCo'; // note: this doesn't make any difference

export default class DummyEditor extends LightningElement { }
```

Metadata

```
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata" fqn="dummyEditor">
<apiVersion>45.0</apiVersion>
<isExposed>true</isExposed>
<masterLabel>DUMMY</masterLabel>
<targets>
<target>lightning__RecordPage</target>
</targets>
</LightningComponentBundle>
```

3) Now add the second component anywhere to a LWC record page

4) Try to open the record (note: it WILL work in App Builder, but not in the console)

Based on what SF support provided me with, it seems that when DummyEditor is compiled, the module for TestCo can't be resolved (i am guessing due to the namespace issues).

**Comment by diervo** [comment]
Hi @az-oolloow, couple of things:

First, Not sure what you mean by `console` but certainly developer console is not supported on LWC.  

As per this:
```
import { TestCo } from 'c/testCo'; // note: this doesn't make any difference
```

This is certainly incorrect and irrelevant since 1) its a default exports 2) you don't need it (dependencies are automatically imported).

I'm not sure what you mean by managed package since you are working with `c` namespace, but anyway, simple composition should work just fine regardless, so not sure what are you trying to do or what's wrong with your environment/deployment.

Lastly, this repository is for LWC open source, and the issue you raised is Saleforce platform specific, which means this is not the right channel for it, so closing this.

Feel free to post your question (please clarify exactly what you are trying to do and what doesn't work in which circumstances) in Salesforce Stack Exchange if you still experiencing issues. But again seems that there is something wrong with your setup.

**Comment by az-oolloow** [comment]
@diervo
1) `console` as in Salesforce UI:
![image](https://user-images.githubusercontent.com/47766072/59581711-15f37f00-9119-11e9-8ceb-4c541540c741.png)
2) Yeah, i took this from SF examples and until Summer 19 the code worked without it
3) 
> I'm not sure what you mean by managed package since you are working with c namespace

In Salesforce, the code in an org can belong to the 'unmanaged' or 'managed' package - this is a model of distribution of code across organizations. 

Managed package means i can publish my code on AppExchange

4) >Lastly, this repository is for LWC open source, and the issue you raised is Saleforce platform specific

Can you point me to a repository for that?

I am a bit surprised how issues are just closed here because as a Salesforce customer, they tell us that LWC is the way to go. And outside of Salesforce (open source or not) i haven't seen many people use LWC as the SPA framework. 

5) > Feel free to post your question (please clarify exactly what you are trying to do and what doesn't work in which circumstances)

I have done that: https://salesforce.stackexchange.com/questions/266154/after-summer19-upgrade-in-apac-ap8-i-am-unable-to-get-to-lwc-record-pages

The issue is that the same code worked in Winter' 19 but stopped working in Summer' 19.

**Comment by diervo** [comment]
This issue was closed because has nothing to do with this repository (we can't humanly scale otherwise). The stack exchange link you sent is indeed the perfect channel for surfacing your problem.

@esalman-sfdc can you take a look and respond accordingly on the stack-exchange post?
