### ISSUE TITLE
WireAdapters Support for v45 newly introduced objects

### ISSUE THREAD

**Issue by JAertgeerts** [salesforce/lwc#1429]
**Is your feature request related to a problem? Please describe.**
WireAdapters such as getObjectInfo and getPicklistValues do not support newly introduced objects for Health Cloud (https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_health_new_objects.htm)

**Describe the solution you'd like**
Support new objects release by release.

**Describe alternatives you've considered**
Apex method that mimics the behavior of the wire adapters.

**Comment by caridy** [comment]
@JAertgeerts this is the wrong channel for specific wire adapters, but we can probably get @davidturissini or @kevinv11n to re-route this to the proper channel.

**Comment by caridy** [comment]
also @Gr8Gatsby can help.

**Comment by Gr8Gatsby** [comment]
I'm following up, stay tuned.

**Comment by JAertgeerts** [comment]
@Gr8Gatsby any news on this?

**Comment by jonathanau** [comment]
@JAertgeerts - Thank you for your inquiry. When using a wire adapter from a `lightning/ui*Api` module, the wire adapter can only access objects supported by UI API. Because the Health Cloud objects have not been enabled for UI API, you will not be able to use them with wire adapters such as `getObjectInfo` and `getPicklistValues`.

More information on this limitation, as well as a link to the list of UI API supported objects, is available at: 
https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.reference_supported_objects

Feel free to reach out if you have any additional questions.

**Comment by JAertgeerts** [comment]
Thanks @johathanau, the ask remains the same - how do we get them supported every release? Is this something you can raise with the UI API team?

**Comment by jonathanau** [comment]
On the UI API team, we are exploring the possibility of enforcing an internal policy where every new standard object must be enabled for UI API access. Additionally, we will be working on getting commonly used objects enabled for UI API. 

At this time, we don't have an ETA for when we will complete the efforts mentioned above.
