### ISSUE TITLE
Child components are not calling disconnectedCallback for custom render()

### ISSUE THREAD

**Issue by k-j-kim** [salesforce/lwc#1435]
### Description

When passing in custom template containing child components to the container component's `render()`, child components are not calling `disconnectedCallback`.

### Version

- LWC: 1.0.2

**Comment by k-j-kim** [comment]
FYI @caridy!

**Comment by caridy** [comment]
After some preliminary investigation, it is clear that we are invoking `clearChildLWC()` abstract operation too early during the re-rendering process. It happens that in the case of re-rendering the same template, the individual elements that are removed will take care of calling disconnectedCallback, but when switching templates, the entire content is wiped out, and there is no way for the rendering logic to disconnected previously inserted custom elements.

`clearChildLWC()` cannot be called during the `renderComponent` abstract operation, I suspect it should be called during `runShadowChildNodesDisconnectedCallback()` abstract operation. The problem now is another... that it might be attempting to disconnect a faulty element because that's also used as part of the error boundary protection mechanism, so we need to be careful here.

On the other hand, once @ravijayaramappa  finished the work on node-reactions, all this is not longer relevant. But we will have to at least fix this in patch.

**Comment by caridy** [comment]
Also, I think our safety nets are not testing the case of replacing a template with a new template when using custom elements that must report the disconnection... seems very edge case.

**Comment by tedconn** [comment]
@ravijayaramappa can we mark this as fixed?
