### ISSUE TITLE
line breaks in text nodes are removed

### ISSUE THREAD

**Issue by tedconn** [salesforce/lwc#1518]
#### Steps to Reproduce

https://developer.salesforce.com/docs/component-library/tools/playground/n4lJ6e_FU/1/edit

#### Expected Results

Line breaks in HTML content should be respected. Look at this fiddle:

https://jsfiddle.net/citizenconn/xbusrc09/

Inspecting the markup in the browser will show you something like this:
```html
<code>
$ npm create-lwr-app
$ webruntime run .
</code>
```
#### Actual Results

Looking at the rendered HTML, one can see that the line breaks in the innerText of the HTML were removed when the component was compiled.

```html
<code c-app_app="">$ create-lwr-app $ webruntime run .</code>
```

### Version

latest from playground

**Comment by caridy** [comment]
This looks like a problem with the transformation after parsing the HTML, or with the parser itself. The compiled code that is relevant to that template is this:

```js
    function tmpl($api, $cmp, $slotset, $ctx) {
      const {
        t: api_text,
        h: api_element
      } = $api;
      return [api_element("code", {
        key: 2
      }, [api_text("$ create-lwr-app $ webruntime run .")])];
    }
```

as you can see, the engine receives a single textNode (via `api_text` api) that contains the crippled text already.

**Comment by pmdartus** [comment]
This is potentially a breaking change. The template compiler has always stripped the trailing whitespaces and line breaks since the inception of LWC. The logic can be found in the compiler [package](https://github.com/salesforce/lwc/blob/6452906aff329f8bde07bc36cbdcee5b3fc97cb6/packages/%40lwc/template-compiler/src/parser/html.ts#L135-L171). As far as I recall, we originally did this to match with Aura's behavior.

We will need to investigate how much it impacts the existing components before making a call on how this should be fixed.

**Comment by caridy** [comment]
@pmdartus I believe the logic here should be changed for the relevant tag names, code, textarea, etc.

**Comment by pmdartus** [comment]
We aren't planning to address this change in the LWC template compiler (at least for now).
