### ISSUE TITLE
lightning-input type="date" does not open date picker on programmatic focus

### ISSUE THREAD

**Issue by mtetlow** [salesforce/lwc#1519]
### Description
lightning-input exposes a focus method. When this focus method is called on type="date", the input is focused but the datepicker does not open. It appears the datepicker only opens if you click on the element. My attempts to simulate a click event on the element via `.click()` have also resulted in the datepicker not opening.
#### Steps to Reproduce
Implement a button and a lightning-input with type="date". On click of the button call `.focus()` on the lightning-input element.

https://developer.salesforce.com/docs/component-library/tools/playground/nL2SB3jcZ/2/edit

#### Expected Results

Datepicker to open
#### Actual Results

Datepicker does not open, but input is focused
### Browsers Affected

Seems to be all
### Version

- LWC: Summer '19

**Possible Solution**

Have the datepicker open or close on focus/blur of the input, or allow the base component to control the focus via an isFocused attribute.

**Comment by ekashida** [comment]
@gonzalocordero Since this doesn't seem to be related to focus delegation, I would say that we should first get clarification from UX as to what should happen when the input receives focus since the native date input for Chrome/Firefox does not open its datepicker unless clicked. If they say that they don't want the datepicker to appear on focus, then Base Components should evaluate the programmatic use case to see if it's something we want to support.

**Comment by gonzalocordero** [comment]
@ekashida yep, you read my mind. I'll open an issue on our side so we can follow up on it. 

@mtetlow Thank you for bringing this up to our attention!

**Comment by joeferraro** [comment]
Just to confirm, is there a known workaround for this? We're really trying not to rebuild the datepicker ...

**Comment by ekashida** [comment]
@joeferraro there is no known workaround. You need to first reach out to SLDS to find out if this is something that can be supported although I suspect not due to accessibility reasons. If it's not, then your UX contact should align with SLDS and come up with a different experience. If it is, then SLDS should add it to their blueprint and then you can file a TD on Base Components to get it added to the datepicker. Ping me if you have further questions.

**Comment by ekashida** [comment]
I checked and saw that you're not a Salesforce employee :)

@sfdciuie has this issue come up before? Can you help find the answer for @joeferraro?
