### ISSUE TITLE
Polyfill `URL` constructor in IE11

### ISSUE THREAD

**Issue by jacobroschen** [salesforce/lwc#1615]
**Description**
When developing in LWC, sometimes developers have a need to gather URL parameters. The easiest way to do this is by utilizing [new URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL). However, this isn't supported in IE11.

**Describe the solution you'd like**
Bring in or develop a polyfill for the `URL` constructor.

**Describe alternatives you've considered**
- Bring in our own polyfill. Ex. https://github.com/zloirock/core-js#url-and-urlsearchparams
- Write our own helper to split & parse the url.

**Comment by pmdartus** [comment]
On IE11, we have decided not to polyfill web plaform APIs because it is hard to draw the line. Since there are so many web platform APIs that are added every years, it is really hard to decide which polyfill we need to bring in: `URL`, `URLSearchParams`, `Fetch`, `Cache`, `Stream`, ...

If you really want to use `URL` and `URLSearchParams` to load the polyfills via static assets or by including them using an LWC module on the platform.

**Comment by ekashida** [comment]
As a general guideline, LWC only introduces polyfills that it needs to use internally. Please consider the above suggestion to load any polyfills you may require.
