### ISSUE TITLE
Datetime Fields using lightning-record-form don't render properly the Date

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#1619]
### Description
Datetime Fields using lightning-record-form don't render properly the Date

#### Steps to Reproduce
Load a dateTime field in a lightning-record-form and you will see the Date part on edit mode is displaying weird characters. They are not properly formated. But when you save it works...

![image](https://user-images.githubusercontent.com/55927613/69008393-e05df680-0941-11ea-9a32-69a4bdcab2a7.png)

### Browsers Affected
Chrome last version

**Comment by caridy** [comment]
@AllanOricil This is not the repo for this kind of issue, this is a problem with a component, but in order to re-route this ticket to the right place, we need more info.

I suspect you're talking about either the playground or the local development environment, if that's the case, then we can loop it the right person. The component works fine if you save it to your org, which is a good indication that the problem is not the component, but the environment where it runs, can you confirm?

**Comment by AllanOricil** [comment]
I created a scratch org from my Dev Org (Dev org not trailhead playground) then pushed the component to this scratch org.

**Comment by caridy** [comment]
ok, in that case I will say: go here https://powerofus.force.com/s/article/How-to-Create-a-Technical-Support-Case-with-Salesforce-Support and open an issue for the lightning global component's team, since this is not part of the engine itself (which is what we have in this repo).
