### ISSUE TITLE
Can't track custom classes

### ISSUE THREAD

**Issue by juvian** [salesforce/lwc#1655]
### Description

On one hand I see in documentation that @track only works with objects created with {}, so I guess classes wouldn't work. But I also read that if you track something lwc won't be able to track, it would give a warning, which I don't see. 

Am I forced to make Attribute a custom component to be able to make it work? 

#### Steps to Reproduce

https://developer.salesforce.com/docs/component-library/tools/playground/P_41sHBv/1/edit

#### Expected Results
When clicking link, template should be updated

#### Actual Results
template is not updated

**Comment by vmarasow** [comment]
I just ran into the same issue with a Map object

**Comment by caridy** [comment]
An obj that can change its properties without external intervention (e.g.: internal state management), is, by our definition, not trackable.

As for Map, Set, and co., we are evaluating whether or not we can observe them (a la VUE), it will take a while for us to settle on that one, a RFC will be needed for sure.

**Comment by juvian** [comment]
This seems to work with simple classes: 
https://developer.salesforce.com/docs/component-library/tools/playground/P_41sHBv/2/edit

**Comment by caridy** [comment]
yes @juvian, you're using a class declaration in that example that is just an illusion, since you update the prototype to be a simple object during construction. That is equivalent to create a regular POJO, or any other object creation process. Those we can track fine... of course, if you're using a getter/setter with some weird behavior, there is nothing we can do about them, but regular value properties, we can track them fine.
