### ISSUE TITLE
Improve dynamic component usability

### ISSUE THREAD

**Issue by jodarove** [salesforce/lwc#1656]
When using dynamic imports alongside dynamic components, the imported module always have the component constructor as `default` property. Ex:

```html
<template>
    <x-lazy lwc:dynamic={customConstructor}></x-lazy>
</template>
```

```js
import { LightningElement, track } from "lwc";
export default class DynamicCtor extends LightningElement {
    @track customConstructor;

    connectedCallback() {
        this.loadCtor();
    }

    async loadCtor() {
        const module = await import("c/customConstructor");
        this.customCtor = module.default;
    }
}
```

I would like to improve the usability of the dynamic components to support the case in which you pass the module definition from a component as the constructor. In that way, the above example can be written like:

```js
import { LightningElement, track } from "lwc";
export default class DynamicCtor extends LightningElement {
    @track customConstructor;

    connectedCallback() {
        this.loadCtor();
    }

    async loadCtor() {
        this.customCtor = await import("c/customConstructor");
    }
}
```

**Comment by jodarove** [comment]
fyi/ @pmdartus @caridy

**Comment by caridy** [comment]
If I understand correctly, you're suggesting that the lwc directive value could accept a module namespace object, and extra the information out of it via the default property, is that it?

**Comment by apapko** [comment]
I'm a bit confused as well. Both examples specify module name in the import call expression. The only observed difference is that in the second example the import resolves the default value vs having to explicitly access it from the module:
```js
const module = await import("c/customConstructor");
this.customCtor = module.default;
```
versus 
```js
this.customCtor = await import("c/customConstructor");
```

**Comment by pmdartus** [comment]
@apapko what @caridy means by the namespace object is the object returns by the `import` invocation. This is different than the component namespace. 

Since all the LWC components are exported via the default export, when importing a component using the `import()` syntax, the component constructor needs to be extracted out of the resolved Module object by accessing the `default` property (example 1). @jodarove proposal is also to allow passing a Module object to the engine when setting a dynamic component and let the engine extract the `default` property if necessary (example 2).

This proposal is an ergonomic improvement and is backward compatible with the current `lwc:dynamic` directive proposal.

**Comment by caridy** [comment]
@pmdartus I'm not talking about the component's namespace object.

> the namespace object is the object returns by the import invocation

that is what is called a namespace object in 262.

I understand that this is an ergonomic improvement, but one that I'm a little hesitated to accept because we don't have a way to validate that what was provided is in fact a namespace object (that's non-observable as far as I can tell, but I can explore more). Based on this, the proposal is really about receiving a constructor, or an object with a default property pointing to a constructor, that's the part I'm not really excited about.

**Comment by pmdartus** [comment]
We can close this for now. We can always come back to this later once there is more adoption with `lwc:dynamic`.
