### ISSUE TITLE
[Question] How to force synthetic shadow DOM?

### ISSUE THREAD

**Issue by noopole** [salesforce/lwc#1742]
### Description

Since version 1.2.2 (https://github.com/salesforce/lwc/pull/1693) it seems that the native Shadow DOM is used instead of the Synthetic Shadow DOM when available.

How is it possible to force Synthetic Shadow DOM polyfill?
or
How is it possible to detect if it's the native or polyfill Shadow DOM that is used?

#### Steps to Reproduce

Load the Synthetic ShadowDOM 1.2.1 and add a Shadow DOM 
=> Polyfilled Shadow DOM

Load the Synthetic ShadowDOM 1.2.2 and add a Shadow DOM 
=>Native Shadow DOM

### Browsers Affected
Chrome and possible all browsers with Native Shadow DOM

### Version
- LWC: 1.2.2+

**Comment by noopole** [comment]
It seems that it is possible to force Synthetic Shadow DOM with the following option:

`host.attachShadow( { mode: 'open', '$$lwc-synthetic-mode$$': true, } )`

But is it possible to force Synthetic Shadow DOM for all the Shadow DOM by default?

`host.attachShadow( { mode: 'open' } )`

**Comment by caridy** [comment]
No, it is not! the main reason here is mostly because the synthetic shadow is not a full-compliance shadow root implementation, there are things that will just not work unless you use LWC, e.g.: slotting doesn't work. So, in order to avoid such confusion, we decided to ask for an explicit flag, being aware of what you're doing is better in this case.

As a workaround, if you really want that to be used, you can patch Element.prototype.attachShadow at the app level after the polyfill is loaded, and add the flag to any call to it before calling the original implementation.
