### ISSUE TITLE
Arrow keys inside table column move focus for custom LightningDatatable

### ISSUE THREAD

**Issue by jinlii** [salesforce/lwc#1766]
### Description
When you create your own data types by extends LightningDatatable, arrow keys do not work inside  <lightning-textarea></lightning-textarea>. Instead it moves focus to another column.

#### Steps to Reproduce
1. 
export default class MyDatatable extends LightningDatatable {
   static customTypes = {
       edit: {
           template: editCol,
       }
   };
}

2. 
` <c-my-datatable key-field="Id" data={data} columns={columns}></c-my-datatable>`

3. 
const columns = [  
    {
        label: 'Comments',
        type: 'edit',
        fieldName: 'id',
    },
];
const recordMetadata = {
    id: 1,
    name: 'John',
    email: 'test@hs.com',
    website: 'url',
    amount: 'currency',
    phone: 'phoneNumber',
    closeAt: 'dateInFuture',
};
 @track data = [recordMetadata];

**Comment by diervo** [comment]
@jinlii unfortunately this is the wrong repository for getting your issue resolved since we do not own those components, so it will be hard for us to assess where the issue is. I suggest you file an issue on the  [app exchange](https://salesforce.stackexchange.com/) and someone from the team will be able to help.
