### ISSUE TITLE
Root components doesn't accept slotted content

### ISSUE THREAD

**Issue by aputinski** [salesforce/lwc#1799]
### Description

When using `@lwc/synthetic-shadow` and `buildCustomElementConstructor`, elements with a `<slot></slot>` render the slotted content outside of the template.

#### Steps to Reproduce

https://github.com/aputinski/lwc-test-case-synthetic-shadow

```html
<template>
  <div><slot></slot></div>
</template>
```

```js
import "@lwc/synthetic-shadow";
import { buildCustomElementConstructor } from "lwc";

import Case from "test/case";

customElements.define("test-case", buildCustomElementConstructor(Case));
```

```html
<test-case>Content</test-case>
```

#### Expected Results
```html
<test-case>
  <div>Content</div>
</test-case>
```

#### Actual Results
```html
<test-case>
  Content
  <div><slot></slot></div>
</test-case>
```

### Version
```
"@lwc/rollup-plugin": "^1.3.2",
"@lwc/synthetic-shadow": "^1.3.2",
"lwc": "^1.3.2",
```

**Comment by caridy** [comment]
This is to be solved by https://github.com/salesforce/lwc/pull/1594

**Comment by caridy** [comment]
btw, this is not strictly about buildCustomElementConstructor, it is just that root elements implemented in LWC do not accept slotted content, that's all.

**Comment by aputinski** [comment]
This seems to be related to `@lwc/synthetic-shadow` though? I get the expected results with native shadow.

**Comment by diervo** [comment]
Yeah this is a known limitation, and one that will take us a while to solve. Think about this as the same with Aura and LWC, you can't have an LWC component have a slot/facet from Aura, because its a framework impedance missmatch.

Synthetic is the same here. 

I think once we merge node-reactions which will use some more native primitives it will allows us to close the gap here, but for the time being, you should use LWC and "leaf" components, meaning that you cant pass slots to it.

**Comment by nolanlawson** [comment]
It's unlikely at this point that we will solve this for synthetic shadow, but there is work in progress to solve this for native shadow: #3655
