### ISSUE TITLE
Missing `hasAttribute()` on a component

### ISSUE THREAD

**Issue by jarrodek** [salesforce/lwc#1810]
### Description
The `hasAttribute()` function is undefined for a component instance.

#### Steps to Reproduce
1. In a component constructor try to check whether an attribute is set

```js
connectedCallback() {
  super.connectedCallback();
  if (!this.hasAttribute('ATTR')) {
    this.setAttribute('ATTR', 'VAL');
  }
}
```

#### Expected Results
Attribute is set when missing

#### Actual Results
```
TypeError: this.hasAttribute is not a function
```

### Browsers Affected
Chrome

### Version
No idea. I am using create-app (or something) command.

**Possible Solution**
Add `hasAtrribute()` to the element.

**Comment by caridy** [comment]
This is a footgun, so it is restricted today. We can evaluate reopening it, but in general, your could is faulty because during construction path no attributes can be added by spec, which means no attribute can be present, by spec.

Additionally, you should not play with tabindex, it is another footgun, let `delegatesFocus` to do its thing.

**Comment by jarrodek** [comment]
The example is wrong. I meant `connectedCallback` and not a constructor. Obviously this example would cause an error when I would try to set attribute in the constructor. That's not the point though.

I known when to use and when not to use tabindex. The component I am working on do need it. I can do the same with `getAttribute` but the question is why we have this inconsistency. For developer experience this function should be enabled along with the other two to set and remove attribute.

**Comment by caridy** [comment]
Ok, in that case, update the description with the correct example, so we can focus on the right thing.

Let me try to separate the two issues here, to see what to do:

1. enabling `this.hasAttribute` in LightningElement.

As I mentioned before, I'm ok to expose this, but maybe adding a warning or error to avoid this being called during construction phase (looking at the code I don't see the restriction in getAttribute anymore, as it is in setAttribute), so, maybe it is fine to just expose it without errors. Do you mind to send the PR?

2. controlling `tabindex` from within the component.

This one is definitely very very problematic. I don't doubt that you know what you're doing, but you don't know what our polyfill is doing, and that's when things go south. If you're using the synthetic shadow polyfill (which is used by platform), then setting the tabindex to something other than 0, breaks the tab sequence, that's why the attribute when using our abstraction is lock down to -1 or 0, plus, other quirks like that, @ekashida is the expert here. Try to rely on the standard equipment here rather than play smart.

**Comment by jarrodek** [comment]
Hey @caridy 
The tab index is not an issue here. That's just a visualization of the problem. I will remove it from the example. Warning to use `setAttribute` in the constructor should be part of linting rules and not compilers, if that's what you mean. Eventually the developer will see the error when they try to run tests as the browser will throw an error :)

**Comment by caridy** [comment]
@jarrodek no, that's not how we do things. Static analysis via linting rules is limited, once you add abstractions, the linter can't really do much there. in LWC we have other runtime means to detect the different lifecycles in the component. 

If you can send the PR, here is the file in question: https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine/src/framework/base-lightning-element.ts#L395-L403
