### ISSUE TITLE
Assert Violation which should not be an error (?)

### ISSUE THREAD

**Issue by jarrodek** [salesforce/lwc#1843]
When developing a component I started receiving an error:

> Uncaught Error: Assert Violation: this.dispatchEvent() should not be called during the construction of the custom element for <awc-input> because no one is listening just yet.

I believe this should not be an error. At most a warning message, preferably info message, ideally no message at all.  There's a case for that.

Consider the following code:

```javascript

export default class Input extends LightningElement {
    @api focused = false;
    
    get focused() {
      return this._focused;
    }

    set focused(value) {
      const old = this._focused;
      if (old === value) {
        return;
      }
      this._focused = value;
      if (value) {
        this.setAttribute('focused', '');
      } else {
        this.removeAttribute('focused');
      }
      this.dispatchEvent(new CustomEvent('focusedchanged', {
        detail: {
          value
        }
      }));
    }
}
```

This causes an error because technically it is dispatched in the constructor. But it is not by my code but rather transformations made by LWC.

**Comment by diervo** [comment]
That code is incorrect, you are using a public field with the same name both with an @api decorator and as a getter/setter pair. That shouldn't even compile, which is the real issue.

LWC will do no transformation on that code other than transforming the decorator.

It's impossible to trigger a setter at construction with our constraints.

Here is your code working properly:
https://developer.salesforce.com/docs/component-library/tools/playground/J14gvGLa8/2/edit

**Comment by diervo** [comment]
I will open a new issue to fix the fact that we have a transformation ordering nuance on the compiler for decorators.

**Comment by jarrodek** [comment]
Then how do you work with boolean attributes? I am so confused by this...

**Comment by caridy** [comment]
@jarrodek first lets talk about the difference between a field and an accessor property. In the code above, you have one class field called `focused`, which is going to be installed on the instance during construction, and its initialization will be carry on during the construction as well.

Then you have an accessor property (getter+setter), this is installed on the class' prototype, and has no initialization.

By combining them both, you're effectively overshadowing them, instance level descriptor (field) will win, because the accessor is on the proto. That's the semantic of the language, so far so good? Btw, this is one of the hazards of fields, people just don't understand that.

Now, in LWC, we do take some liberties for the sake of perf, and when you decorate a field, we actually install it in the proto, and initialize it on the constructor. The issue that you're seeing here is that the initialization of the field `focused` actually hits the accessor (which exists in the prototype), and the setter will attempt to dispatch the event. That explains the why you're seeing this, I hope.

I do agree with @diervo that we should throw at compile time when this case exist, we did tried that, but there were some breaking changes (some folks doing similar stuff), that's why we took that bullet. cc @pmdartus, eventually, once we have a missing piece in our platform, we might attempt to improve this (looking at you @reiniergs).

Finally, your code is definitely faulty. it has two fundamental problems:
  a) as @diervo pointed out, you should never attempt to dispatch an event if you're disconnected, during construction, you're disconnected, but I understand this is somehow a consequence of LWC transformation that is hard to reasoning about, we should improve that.
  b) you're implementing your own focus behavior, which is in general a very bad sign, don't do that, let the system handle the focus notifications for you. You can talk to @ekashida if you want to learn more about focus behavior in web components in general. He is our in-house expert on the subject.

**Comment by caridy** [comment]
oh, more info about this here: https://github.com/salesforce/lwc/issues/1525
