### ISSUE TITLE
 Can't resolve 'fs' in 

### ISSUE THREAD

**Issue by Yuv23** [salesforce/lwc#1941]
When I am trying to use fs module in lwc component its causing error.

Please suggest how to include this in my project.

**Comment by jasonsilberman** [comment]
The `fs` module is most likely not available in your web component because you are running the component in a browser environment, and the `fs` module is part of node.

If you are trying to read files from disk as part of the component, that probably won't work and you might want to try to come up with another way of accomplishing what you are doing.

Could you provide some more details about what you are trying to do?

**Comment by Yuv23** [comment]
hi @jasonsilberman thanks for reply 

I want to implement express server with https. To request from client I need to provide certificate details as follows : 
![image](https://user-images.githubusercontent.com/39365690/85360078-be5ecf00-b535-11ea-893e-34b866df12a2.png)

Please let me know alternative.

**Comment by pmdartus** [comment]
I don't think I still understand what you are attempting to do. The `http` and `https` packages are NodeJs only modules that can't be used in an LWC component running in a browser. Are you looking to send an HTTPS request from your LWC component to an external service? For this, you can use [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) or [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).  

We can keep talking about your specific issue, but I will close this issue since it is unrelated to LWC.

**Comment by Yuv23** [comment]
@pmdartus @jasonsilberman  I wanted to setup express with ssl for my local host code is like that :

![image](https://user-images.githubusercontent.com/39365690/85396522-896f6e00-b56f-11ea-9225-31e97bdbea19.png)

 when I am using fetch to access server I am getting DEPTH_ZERO_SELF_SIGNED_CERT.. any resolution for this ?

**Comment by pmdartus** [comment]
This issue is unrelated to LWC, and probably related to your NodeJs setup. Do you have a small repro to share? This will make it easier to understand what is wrong in your Node setup.
