### ISSUE TITLE
Replace eval With window.Function

### ISSUE THREAD

**Issue by BatemanVO** [salesforce/lwc#2005]
While working on a new Lightning Web Component, I noticed during an error prompt that an error occurred when running the `eval` function:

![Capture](https://user-images.githubusercontent.com/20998142/90440444-16283b00-e08c-11ea-993d-cbe1c456ccbd.PNG)

I don't know if the function it means is the built-in JavaScript eval, but [MDN recommends never using `eval()` because it has major security vulnerabilities and is extremely non-performant](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!):
> eval() is also slower than the alternatives, since it has to invoke the JavaScript interpreter, while many other constructs are optimized by modern JS engines.
> Additionally, modern javascript interpreters convert javascript to machine code. This means that any concept of variable naming gets obliterated. Thus, any use of eval() will force the browser to do long expensive variable name lookups to figure out where the variable exists in the machine code and set its value. Additonally, new things can be introduced to that variable through eval() such as changing the type of that variable, forcing the browser to re-evaluate all of the generated machine code to compensate.

I don't believe this issue is specific to Lightning Web Components, but with Salesforce's Lightning framework overall, so I'm not sure where the best place to bring up this possible issue is. However, if `eval` is being used under the hood, MDN has a recommendation to use `window.Function()` instead in that same link. I don't see any reference to `eval` being called in this repo, but we might be able to significantly improve the efficiency of Lightning if we can replace it somewhere behind the scenes if it is being used.

**Comment by caridy** [comment]
Hey @BatemanVO, thanks for the issue. I will do my best to try to explain:

`Function` constructor is not equivalent to `eval`, in fact they are quite different. One runs indirect evaluation, the other one runs direct evaluation, which has implications on how bindings (variables) are resolved while evaluating the code. LWC does not use either of those form of evaluation. I'm afraid that there is nothing to be done here in this repo.

What MDN is reference to is for authors, those who are writing code, like you, to avoid using eval, and in general, avoid any kind of dynamic evaluation of code in JS. That is a choice, and we highly recommend to follow those guidance, but we will not enforce it at the different layers. Why not? because it breaks a lot of code that uses those capabilities already.

Please, feel free to reopen the issue if you have a concrete example, or a concrete recommendation about what we should do about this.

**Comment by BatemanVO** [comment]
The error mentioned in the screenshot occurs if an expression in the HTML file has a problem. What that suggests is that, somewhere under the hood, the HTML's JS expressions are being evaluated using the native `eval` function - if so, it looks like using `window.Function()` to basically create an IIFE is MDN's recommended alternative to using `eval`.

I don't see any code in this particular repo using `eval`, but the implication from errors thrown while parsing the HTML JS expressions in LWCs is that `eval` is being called somewhere within the Lightning framework. Is there somewhere we can follow up to see if that's the case? Alternatively, is there a clearer explanation of what `eval` function is being called when that error is thrown?
