### ISSUE TITLE
Current implementation of scoped IDs breaks SVG filters

### ISSUE THREAD

**Issue by CatJazz** [salesforce/lwc#2063]
How do I make the svg filter option work?  

This shows two circles in codepen, one with a blur.  It is also fine on a Visual Force page.
`
<svg width="230" height="120" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <filter id="blurMe">
      <feGaussianBlur stdDeviation="5"/>
    </filter>
  </defs>
  <circle cx="60" cy="60" r="50" fill="green" />
  <circle cx="170" cy="60" r="50" fill="green" filter="url(#blurMe)" />
</svg>`

In lwc, there is no blur.  Inspecting DOM shows filter to be present, but it is empty.

**Comment by CatJazz** [comment]
Hi diervo, not sure what you mean exactly.  Filter claims to be a supported tag, or do you mean something else? https://developer.salesforce.com/docs/component-library/documentation/en/lwc/use_svg_in_component.

**Comment by diervo** [comment]
Yes I know its technically supported, but you are reporting an issue when apply a set of attributes are you not? We do special filtering of certain attribute for security reasons, hence my ask to double check. 

If you can provide us a repro example on our playground that will certainly speed up things.

**Comment by CatJazz** [comment]
You put the svg from above inside a <template> and save it.  It don't work in lwc.  Can't get any more simple.

**Comment by jodarove** [comment]
`filter` is a supported tag for the svgs. the issue here seems to be the template scope ids. the id of the filter tag (`blurMe`) is replaced in the generated html to, eg: `(blurMe-1)` and the url `url(#blurMe)` keeps referencing to the old id.

@ekashida will know more on the solutions.

Note: a simple repro is to add a component with the following template:
```html
<template>
    <svg width="230" height="120" xmlns="http://www.w3.org/2000/svg">
        <filter id="blurMe">
            <feGaussianBlur stdDeviation="5"/>
        </filter>

        <circle cx="60" cy="60" r="50" fill="green" />

        <circle cx="170" cy="60" r="50" fill="green"
                filter="url(#blurMe)" />
    </svg>
</template>
```
the expected output should be like in the example from [mdn](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter) (2 circles, 1 of them blur) but the actual is just one circle.

**Comment by ekashida** [comment]
@jodarove is correct, we are hitting an edge case in the shadow DOM implementation of scoped ids. We should be parsing the value of the `filter` attribute so that the reference in its `url()` value is preserved.

As it would be an observable change, the fix for this may take some time as we would need to consider the impact to existing SVG implementations.

In the meantime, my suggestion is that we work around this in a future-compatible way by setting both attributes manually:

```html
<template>
  <svg width="230" height="120" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <filter data-id="filter-blur">
        <feGaussianBlur stdDeviation="5"/>
      </filter>
    </defs>
    <circle cx="170" cy="60" r="50" fill="green" data-id="circle-blur" />
  </svg>
</template>
```

```js
import { LightningElement } from 'lwc';

export default class extends LightningElement {
  initialRender = true;
  renderedCallback() {
    if (this.initialRender) {
      this.initialRender = false;
      this.template.querySelector('[data-id=filter-blur]').setAttribute('id', 'blurMe');
      this.template.querySelector('[data-id=circle-blur]').setAttribute('filter', 'url(#blurMe)');
    }
  }
}
```

**Comment by ekashida** [comment]
Related to #1350

**Comment by CatJazz** [comment]
Thanks ekashida.  I tried your suggestion, but it does not look the same as the mdn example.  The blur appears to be inside the circle, rather than making the edges more diffuse.

**Comment by ekashida** [comment]
@CatJazz I just copy/pasted my [example](https://github.com/salesforce/lwc/issues/2063#issuecomment-716514721) into the [playground](https://developer.salesforce.com/docs/component-library/tools/playground) and got the same result as the MDN example.
