### ISSUE TITLE
setCustomValidity is not a function in lightning-input-field

### ISSUE THREAD

**Issue by sagar2dumbre** [salesforce/lwc#2079]
I am trying to add a custom error message for `lightning-input-field`.

<lightning-input-field field-name="Legal_Entity__c" variant="label-stacked">

```
onclickHandler(event){
    let searchCmp = this.template.querySelector('lightning-input-field');
    let searchvalue = searchCmp.value;
    if (!searchvalue) {
      searchCmp.setCustomValidity('Name value is required');
    } else {
      searchCmp.setCustomValidity(''); // clear previous value
    }
    searchCmp.reportValidity();
}
```

I am getting below error saying 

> searchCmp.setCustomValidity is not a function

Is `setCustomValidity` not supported for `lightning-input-field`? If yes, what is the recommended way to achieve custom error messages?

**Comment by pmdartus** [comment]
Thanks for opening this issue @sagar2dumbre. Since Lightning base components are outside the scope of the LWC framework, I will close the issue. 

[Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) is the right forum to post questions related to Lightning base components and best practices.
