### ISSUE TITLE
@track does not consider new keys in objects

### ISSUE THREAD

**Issue by itsmebasti** [salesforce/lwc#2249]
### Description
@track combined with a getter does not consider new keys in objects.
So setting value2 in the following example will not update the user interface, because it was not initially available, thus it seems not to be tracked by the @track annotation.
#### Steps to Reproduce
Write a getter that iterates over some tracked js-object values and add new keys to this object.

https://webcomponents.dev/edit/u6Wk6srXcMDmJrzfnibI/src/app.js

```js
  @track tracked = {value1: "Hello"};

  get words() {
    return Object.entries(this.tracked)
              .map(([key, value]) => ({key, value}));
  }

  setValue1(evt) {
    this.tracked.value1 = "Hello World";
  }

  setValue2(evt) {
    this.tracked.value2 = "World";
  }

  reset(evt) {
    this.tracked = {value1: "Hello"};
  }
```

#### Expected Results

The component should update whenever my tracked object changes.
#### Actual Results

It only rerenders, when existing keys are updated.
### Version

- LWC: x.x.x

**Possible Solution**

use the "defineProperty" trap in the proxy handler to mark affected objects as dirty
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/defineProperty
**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gelliott181** [comment]
Thank you for finding this, I thought I was going crazy when tracked objects weren't updating as expected. Since this effects properties by key, I'm assuming it also means tracked arrays are no longer "push aware". Is that something you've seen too?

**Comment by pmdartus** [comment]
Thanks for reporting this issue @itsmebasti.

What you are observing here is an interesting side-effect of the LWC mutation tracking. **The engine only re-renders a component if a property accessed during the previously rendering cycle is updated**. This is an optimization to prevent component over-rerendering. Let me illustrate this with a concrete example.

```js
import { LightningElement, track } from 'lwc';

let renderedCount = 0;

export default class App extends LightningElement {
    @track
    state = {
        usedCounter: 0,
        unusedCounter: 0,
    };

    connectedCallback() {
        setInterval(() => {
            this.state.unusedCounter++;
        }, 500);
    }

    renderedCallback() {
        console.log('>> renderedCallback', ++renderedCount);
    }
}
```

```html
<template> Counter {state.usedCounter} </template>
```

**Live example: [link](https://webcomponents.dev/edit/xKjgjhy6T0kQsaL69Jj5/src/app.js)**

In the above example, the track `state` object contains 2 properties `usedCounter` and `unusedCounter`. The `state.usedCounter` is the only property accessed in the template. After connecting, the `state.unusedCounter` is incremented at a fixed interval. If you open your browser console, you can see that this component is only rendered once.

During the first render cycle, the LWC engine record that `state.usedCounter` is accessed. Any mutation applied to the `state` that doesn't affect `usedCounter` will be ignored by the engine since it doesn't impact the DOM. Updating `state.unusedCounter` or adding a new property to `state` will not trigger a re-render.

Now going back to your example. In your case, all the property accessed are in the `words` getter. Internally in `Object.entries`, enumerates the keys on the `tracked` object, for each key it retrieves the value and maps it to the `[key, value]` tuple. So from the engine perspective, the only property accessed during the template rendering is `tracked['value1']`. Adding `value2` to `tracked` will not trigger a rendered as discussed above.

To force the engine to re-render your component when adding a new property you have to make it understand that `tracked` has changed. The right way to do this is to create a brand new object with both `value1` and `value2`.

```js
setValue2(evt) {
    this.tracked = {
        ...this.tracked,
        value2: "World"
    };
}
```

**Live example: [link](https://webcomponents.dev/edit/V00YdUidS5hNKLb1vn1m/src/app.js)**

I will close this issue since we are not planning to change the existing mutation tracking behavior.

---

Your comment @gelliott181 is really interesting as well! `Array.prototype.push` doesn't suffer from the same issue as `Object.entries`. Let's adapt the previous example to explain this.

```js
import { LightningElement, track } from 'lwc';

let renderedCount = 0;

export default class App extends LightningElement {
    @track
    state = ['hi'];

    connectedCallback() {
        setInterval(() => {
            this.state.push('hi');
        }, 500);
    }

    renderedCallback() {
        console.log('>> renderedCallback', ++renderedCount);
    }
}
```

```html
<template>
    <template for:each="{state}" for:item="item"> 
        {item} 
    </template>
</template>
```

**Live example: [link](https://webcomponents.dev/edit/2L6k5fe5UILmQ7ALoVlA/src/app.js)**

In this case, the component does re-render every time that `this.state.push('hi')` is invoked. 

The `for:each` template directive can be assimilated to `Array.prototype.map` method. To map over the `state` array, first the `length` property is extracted to know how many items the array contains. Then each item is accessed from the array. At the end of the first rendering cycle the following properties are tracked by the engine: `state.length` and `state[0]`.

JavaScript engine does 2 internal operations when `Array.prototype.push` is invoked. First set the item at the current `length` index and increment the `length` property. Since the `state.length` has been accessed during the previous rendering cycle, the component will re-render.

**Comment by itsmebasti** [comment]
Wow, thanks for the detailed explanation!
Maybe some design feedback here, if a developer decides to @track an object you might consider extending the mutation tracking since this is what a developer expects from the annotation when using it.
In other words, all developers should be aware, that changes will affect the render mechanisms when they decide to track the affected object.
But never mind, it's also fine if this is by design, so we at least can count on it and know how to handle it 👍
