### ISSUE TITLE
Input with regex pattern does not work

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2259]
#### Steps to Reproduce
Add a pattern like the one shown below and check that eslint will complain about it. 

![image](https://user-images.githubusercontent.com/55927613/109646172-c0127500-7b4f-11eb-89cf-9f5d4b84e756.png)

Save your component and go to the local dev server page to verify it could not be compiled

![image](https://user-images.githubusercontent.com/55927613/109646246-dddfda00-7b4f-11eb-96bc-9e019ea87811.png)

It can't be compiled anywhere

![image](https://user-images.githubusercontent.com/55927613/109647555-585d2980-7b51-11eb-8979-9e36f12a575a.png)

Now do the eslint suggestion of escaping `.` to make it `\.{0,40}` and verify that the component compiles, but the pattern is no longer doing what it should because we escaped the `dot` making regex treat it like a dot character

https://webcomponents.dev/edit/N3IN42GJ5FHxq2fQC7sN/src/app.html

Now add the escape character to allow the lwc engine to compile the component, wait until the component is mounted in the dom, inspect the page, go to the input and remove the escape character to be like this

![image](https://user-images.githubusercontent.com/55927613/109648576-acb4d900-7b52-11eb-993d-8624bf0f182b.png)

Verify that the regex expression is valid, and it does work.

Then I  also thought about writing what `<lightning-input>` renders by myself and LWC also does not allow me to do it

![image](https://user-images.githubusercontent.com/55927613/109649052-441a2c00-7b53-11eb-95c3-a0c82a9c5908.png)

#### Expected Results
Regex pattern should be accepted as it is said in the docs https://developer.salesforce.com/docs/component-library/bundle/lightning:input/example

#### Actual Results
Regex pattern can't be used in inputs

### Browsers Affected
Any

### Version
Latest

**Possible Solution**

**Comment by AllanOricil** [comment]
I found a workaround which was to use js after the component is rendered to fix the regex

![image](https://user-images.githubusercontent.com/55927613/109651905-03bcad00-7b57-11eb-91ce-defdb41d9469.png)

**Comment by AllanOricil** [comment]
I decided to use this other approach to solve the problem instead of manipulating the dom to fix it.

![image](https://user-images.githubusercontent.com/55927613/109684388-1f847b00-7b78-11eb-94e0-dec67b245cfc.png)

**Comment by pmdartus** [comment]
The curly braces are interpreted as an expression, which is the current behavior. I would recommend defining the pattern in your component class and pass the pattern as an expression to the component via the template.  

```js
export default class extends LightningElement {
  pattern = ".{0,40}";
}
```

```html
<template>
  <lightning-input pattern={pattern}></lightning-input>
</template>
```

**Comment by AllanOricil** [comment]
@pmdartus the example in the docs are not saying that. You should not close this as it is not working as designed. And this is the only parameter that does not follow html 5 guidelines

Doc Example
https://developer.salesforce.com/docs/component-library/bundle/lightning:input/example

**Comment by pmdartus** [comment]
You are right in saying that the documentation is incorrect since the pattern passed to the `<lightning-input>` might be incorrectly interpreted as a template expression. I did report internally to the team in charge of the lighting component to adjust the documentation.

As stated previously, the usage of curly braces in the template is interpreted by the LWC compiler as an expression. This is true for attribute values and text content. The attribute value `.{40,0}` is interpreted as a potential and rejected by the compiler. I don't think it makes sense to add more complexity to the compiler to handle this special case on the `pattern` attribute when there is a workaround to lift the ambiguity.

>  does not follow html 5 guidelines

@AllanOricil Could you explain what you mean by HTML 5 guidelines in the context of this issue?

Since there is no action item on the LWC team, I think it make sense to close this issue for now. However, nothing prevents us from discussing on this issue.

**Comment by AllanOricil** [comment]
@pmdartus I mean that all the other standard html 5 input props can be added inline, like step, min, max...
While the pattern prop is an exception to this. Seems weird. But if you say it is working as designed, that is fine. I just think it is not a good DX. I'm sure someone else will stumble upon this problem.
But that is fine. I just wanted to report it and since there is a workaround it is ok for me.
