### ISSUE TITLE
Add support to mirage js

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2264]
Is your feature request related to a problem? Please describe.
Sometimes I'm developing components while another developer is working on the controllers to increase throughput. In this scenario, it would be nice if I could create a mock server using mirage js to mock apex requests. This approach is commonly used in other front-end frameworks projects that have huge teams working together.

Describe the solution you'd like
Add support to mirage js

Describe alternatives you've considered
Hard code responses in my Source code and when the component is ready I just remove all of them. But this requires rework and I have to open PRs to remove, then waste time going through the pipeline and PR reviews.

Additional context
NA

**Comment by AllanOricil** [comment]
related https://github.com/forcedotcom/lwc-dev-server-feedback/issues/109

**Comment by pmdartus** [comment]
The issue you opened against forcedotcom/lwc-dev-server-feedback repo is sufficient. Since this feature request is out of the scope of the core LWC framework I will close this issue.

Here are a couple of pointers if you want to use [mirage.js](https://miragejs.com/) to mock the Apex callout. If you are using the [@lwc/jest-preset](https://github.com/salesforce/lwc-test/tree/master/packages/%40lwc/jest-preset) to run your test using jest, you have to provide a mock implementation for all Apex imports. You can find a mock example in the [lwc-recipes](https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/apexImperativeMethod/__tests__/apexImperativeMethod.test.js#L6-L14) repo.

In the example above the mocked Apex module does return a function resolving to a value defined in your test. On the other hand, Mirage.js is mocking outbound HTTP requests. So instead of returning a function resolving a value, you can replace this mock function with a plain `fetch` request. This approach does allow mirage.js to intercept the request.

It is pretty cumbersome to manually mock all the apex import in each test file, so I would recommend using [moduleNameMapper](https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring) or [manual mocks](https://jestjs.io/docs/en/manual-mocks) approach to avoid repeating this code between test files.

**Comment by AllanOricil** [comment]
@pmdartus I don't want to use mirage js with jest. I want to use it while developing and to use it alongside Cypress Js to run e2e tests.  This way I can quickly test web apps built with lwc without the need of having anything from the server.  What do you think?

**Comment by pmdartus** [comment]
This sounds good approach for end-to-end testing. That said, I am not familiar enough with the way the lwc-dev-server works to help you with this.
