### ISSUE TITLE
Debounced functions looses their target and currentTarget

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/lwc#2265]
### Description

Function that were debounced and attached to the input had lost target (`target` is equals to top component and `currentTarget` equals to `null`

It has same effect if you put debounce func inside your handler

#### Steps to Reproduce

1. Create component
2. Add input type text to it
3. Create debounce function
4. Create handler
5. bind handler and debounce `handlerDebounced = debounce(this.handler.bind(this), 250)`
6. attach binded handler to the input onkeyup listener `onkeyup={handlerDebounced}`

https://webcomponents.dev/edit/ToWqRRoQaxWdxTQLANxP/src/app.html

```js
debounceFunc = (func, wait = 100) => {
    let timeout;

    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };

        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
};
```

#### Expected Results

`target` and `currentTarget` are from input element

#### Actual Results

`target` and `currentTarget` are different

### Browsers Affected
All browser

### Version

- LWC: Salesforce latest

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pmdartus** [comment]
The current implementation is behaving according to the specification: [example](https://jsfiddle.net/5uks4xye/6/). This has to do with the timing you access the `target` and `currentTarget` value on an event. As an event bubbles in the DOM, the `target` and `currentTarget` values are updated. This process is called event retargeting. 

So instead of passing the event directly to the debounced function, you can dereference the properties you are interested in in the handler and invoke the debounced function with the cached values: [example](https://jsfiddle.net/1Lsjhnx5/2/).

**Comment by gonardfreeman** [comment]
@pmdartus many thanks!
