### ISSUE TITLE
Reduce initial load time

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/lwc#2276]
**Is your feature request related to a problem? Please describe.**
Our product has a lot of components inside and initial load time is significant (30 and more seconds).
After investigation I've found out that it LWC engine loads **all** components at once as JS string.

**Describe the solution you'd like**
- Dynamic load - load components by request from user.
- Do not load all components at once - same as dynamic but engine will load only rendered components (template if:true or something else).

Is there any advices that you could give to decrease initial loading time?

**Comment by pmdartus** [comment]
> After investigation I've found out that it LWC engine loads all components at once as JS string.

Many factors might influence the initial page load time: server load, network latency, machine performance, module size, etc. That said LWC components packaging and delivery in Salesforce Lightning Experience is out of the control of the LWC framework.

The [Lightning Experience Performance Optimization](https://trailhead.salesforce.com/content/learn/modules/lightning-experience-performance-optimization) trailhead module contains resources that might help you. Otherwise, I would also recommend getting in touch with Salesforce support to conduct an investigation.
