### ISSUE TITLE
How to add condition render with expression in lwc?

### ISSUE THREAD

**Issue by ajay312** [salesforce/lwc#2366]
We have a requirement where we need to add condition to render templates 

type = input ---input template
type = select --- select template

we will get type from a json
Following is my template with loop .Need dynamic condition to render template

      <template if:true={fields}>
        <template for:each={fields} for:item="field">
          <div class="slds-form" key={field.key}>
            <div class="slds-form-element slds-form-element_horizontal">
              <label
                class="slds-form-element__label"
                for="horizontal-input-id-01"
                >{field.templateOptions.label}</label
              >
              <div class="slds-form-element__control" if:true={field.type==='input'}>
                <input
                  type="text"
                  placeholder="Placeholder text…"
                  class="slds-input"
                />
              </div>
            </div>
          </div>
        </template>
      </template>

              **<div class="slds-form-element__control" if:true={field.type==='input'}>**
@pmdartus 
Where type of value change in every object.
.Any suggestions to accept dynamic type or how to pass argument to getter method

**Comment by nolanlawson** [comment]
It seems that what you want is to run arbitrary JavaScript inside of `if:true` rather than just a getter (`if:true={field.type==='input'}` in your example). You have a few options.

One option is to create another component and pass the parameters in to that component:

```html
<template for:each={fields} for:item="field">
  <c-my-field-component field={field} key={field.key}></c-my-field-component>
</template>
```

... then you would do your conditional rendering inside of the `render()` function for `<c-my-field-component>`.


The other option is to create a custom getter on the `fields` objects. For example:

```js
export default class extends LightningElement {
  fields = [/* ... */]
  fieldsWithCustomGetter = fields.map(field => ({
    ...field,
    get fieldTypeIsInput () { return this.type === 'input' }
  }))
}
```

... then you would use `if:true={field.fieldTypeIsInput}` in your template.

Closing for now, please reopen if that doesn't answer your question! 🙂
