### ISSUE TITLE
disconnectedCallback() simply not firing until reconnection [Salesforce]

### ISSUE THREAD

**Issue by LukeKoz** [salesforce/lwc#2398]
### Description

This is on Salesforce. I have raised a case and posted on the community. But I think it would be good to get some input from you guys.

I've been working on a complex component which uses event listeners and interval-based operations. I am required to close all that off when the component has been disconnected. Unfortunately, `disconnectedCallback()` is simply not executing no matter what I do.

To investigate further, I broke this down and made the most basic component I could:

```javascript
connectedCallback() { console.log('connectedCallback'); }
disconnectedCallback() { console.log('disconnectedCallback'); }
````

The `disconnectedCallback` function is still not firing.

So I created a new org to see if it was org-specific. Nope - still not firing.

The only time it does fire is when you go back to where the component is placed - it will disconnect the component and then reconnect the component immediately after. Which is not useful.

#### Steps to Reproduce

1. Copy the above code into a basic LWC and add to a Lightning page.
2. Navigate to another page

#### Expected Results

`disconnectedCallback` is displayed in the JS console

#### Actual Results

`disconnectedCallback` is not displayed in the JS console.
It is display however when you come back to the same page with the component and it reconnects. Only for it to reconnect again.

### Browsers Affected

Only tested in Chrome so far

### Version

Summer '21

**Comment by pmdartus** [comment]
On Salesforce, when using standard navigation previously visited pages are cached and not unmounted from the DOM. After navigating away from a page and then pressing the browser back button, the cached page is displayed instead of rendering a brand new page. The last time I checked, Salesforce can cache up to 5 pages before being unmounted from the DOM.

Since those components are still live in the DOM even after navigating away from the page the `disconnectedCallback` will not be invoked. The `disconnectedCallback` will only be invoked after the standard navigation reaches once the cache is full. To my knowledge the is no way to detect listen for navigation events from a component.

I will close this issue for now, since there is not an LWC framework issue.
