### ISSUE TITLE
Array.prototype.indexOf performance degradation

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/lwc#2446]
### Description

Locker service cause performance degradation of native indexOf function.

#### Steps to Reproduce

Create the first array.
`var a = [...Array(300).keys()];`
Create the second array of 50 elements.
`var b = [...Array(50).keys()];`

create loop to iterate over 1st array and check if el from it is present in 2nd array.
```js
for (var i = 0; i < a.length; i++) {
  if (b.indexOf(a[i]) > -1) {
    console.log(a[i]); 
  }
}
```

debug showed that after each call of indexOf function on Proxied array engine performs loop on those 50 elements:
```js
function getFilteredValues(so, filtered) {
   // Gather values from the filtered array
   const ret = [];
   filtered.forEach((item) => {
     const value = item['rawValue'];
     ret.push(value ? filterEverything(so, value) : value);
   });
   return ret;
}
```
which causes significant performance degradation because instead of 300 iterations we have `15000 = (300 * 50)`

#### Expected Results
No additional iterations on indexOf function call

#### Actual Results
additional 14700 iterations.

### Browsers Affected
Every browser

**Possible Solution**
Do not override native functions

**Comment by nolanlawson** [comment]
Thanks for reporting. This seems to be the same as the issue described [in this StackExchange answer](https://salesforce.stackexchange.com/a/296044) – `getFilteredValues` slowing down Array prototype APIs.

This is due to the current version of Locker. The in-development version of Locker should not have this same problem. For the time being, I think this issue can be closed, since there is nothing for LWC to do about this issue, and Locker is aware of the problem. Please let me know if that answers your question.

**Comment by gonardfreeman** [comment]
Yep! Thanks!
