### ISSUE TITLE
Could you create a Dependency Loader which would not require us to call LoadStyle or LoadScript?

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2511]
**Is your feature request related to a problem? Please describe.**

I'm working with fontawesome and I couldn't use loadStyle outside of a LightningElement, because when I tried, it threw the following exception

![image](https://user-images.githubusercontent.com/55927613/134886605-62e54181-1a97-4e90-bbe2-c7e43935fbff.png)

And this has already been reported as a known Issue: https://trailblazer.salesforce.com/issues_view?id=a1p3A000001SHoDQAW

This is how I tried to do and end up getting that exception

fontawesome.js
````js
import fontawesome from '@salesforce/resourceUrl/fontawesome';
import { loadStyle } from 'lightning/platformResourceLoader';

export function load(){
      loadStyle(this, fontawesome + '/css/all.css')
      .then(() => {
          console.log('css loaded successfully'); // just to test
      })
}

````

parentComponent.js
````js
...

import { load } from 'c/fontawesome';

...
````

So, to make it work, I had to turn that into a component, and add it to the template, like this:

fontawesome.js
````js
import fontawesome from '@salesforce/resourceUrl/fontawesome';
import { loadStyle } from 'lightning/platformResourceLoader';
import { LightningElement } from 'lwc';


//unfortunately we can't use "loadStyle" outside of a LightningELement. If you try, it will throw an exception.
//that is the reason for me to export a class that extends LightningElement
export default class Fontawesome extends LightningElement(){
    constructor(){
        super();
        loadStyle(this, fontawesome + '/css/all.css')
        .then(() => {
            console.log('css loaded successfully');
        })
    }
}

````
parentComponent.html
````html
<template>
    <div>
        <c-fontawesome></c-fontawesome>
        <i class="fas fa-user"></i>
    </div>
</template>

````

but as you can see, this looks horrible and I have to write more. Also, for people who worked with Webpack, Rollup or any other bundler, this is counter intuitive. We never import a CSS lib in the html/template. It is like adding a <style> tag by hand instead of using a CSS loader to resolve the dependency for us. In the end, those bundlers put the css inline into the js, or behind the scenes they call a method to load the css, like what LWC does at the moment. So, for me, calling a method is not a problem. The problem is that I need to import the resource and also call the method, as well as not being able to use `loadStyle` or `LoadScript` outside of a LightningElement. Why can't I use those methods outside of a LightningElement? 

So I would like to propose a change. Couldn't you let us simply do this:

parentComponent.js
````js
...
import fontawesome from '@salesforce/resourceUrl/fontawesome/css/all.css';
...
````

or this
parentComponent.css
````css
...
import fontawesome from '@salesforce/resourceUrl/fontawesome/css/all.css';
...
````

See how much easier it is for me to use fontawesome inside my component. I would not need to write a separate component, I would not need to call `loadStyle`, I would feel Im working as If I were using the bundlers Im used to. 

**Describe the solution you'd like**
It is described above

**Describe alternatives you've considered**
It is described above

**Additional context**
N/A

**Comment by AllanOricil** [comment]
Another thing I noticed is that the asset only starts to load after the parent component is mounted. This is not good. You could break it into multiple chuncks, if you load styles inside the js, and require them while the parent is loading. This way, considering my example with fontawesome, the User would not see a broken Icon until `loadStyle` is resolved.

**Comment by pmdartus** [comment]
> Also, for people who worked with Webpack, Rollup or any other bundler, this is counter intuitive. We never import a CSS lib in the html/template. It is like adding a <style> tag by hand instead of using a CSS loader to resolve the dependency for us.

Webpack [style-loader](https://webpack.js.org/loaders/style-loader/) and alternatives provided by other bundlers are inherently incompatible with the way Shadow DOM. All the bundlers are injected the imported styles at the document level and will not match with elements rendered inside LWC components. The  `loadStyle` requires the component as the first argument to identify in which shadow tree the stylesheet should be injected. 

It doesn't matter much today on the Salesforce platform as we are running an emulated version of shadow DOM (because of backward compatibility with IE11). Once we officially drop support for IE11 and once we enable native shadow DOM on the platform, knowing where to inject the stylesheet will be important.

You example with `<c-fontawesome></c-fontawesome>` and `<i class="fas fa-user"></i>` will certainly break with native shadow DOM enabled as the font awesome stylesheet will be scoped to `<c-fontawesome>` shadow tree.

> Another thing I noticed is that the asset only starts to load after the parent component is mounted. This is not good.

The `@salesforce/resourceUrl/*` modules export the effective URL of the static resource. As static resources can contain one or multiple files from a ZIP file, it is impossible to prefetch the correct file in advance. 

I would recommend loading the font-awesome stylesheet via a CSS file in your `<c-fontawesome>` component. LWC component stylesheets are bundled with your component code, which would prevent the flash of unstyled content.

**Comment by AllanOricil** [comment]
@pmdartus thank you for explaining that. 

But there is another question here I would like you to answer:

If we write:

`import fontawesome from '@salesforce/resourceUrl/fontawesome/css/all.css';` 

couldn't you build the component in a way that you would handle the calls of loadStyle and loadScripts? I think you can because you have the exactly path of the resource and its type, in this case it is a .css file.

If you can, but you don't do it. Can you explain why?  It is really weird to let the developer to handle it. I think it is because of the shadow dom thing you explained above, but just want to confirm to see if I understood it correctly.

Also, I think it is bad for the initial loading time performance because we need to wait the JS to load, then wait the loadStyle/loadScript to be reached, and then wait the promises to be resolved. Am I right?

**Comment by pmdartus** [comment]
> If you can, but you don't do it. Can you explain why?

No, it is unfortunately impossible. Static resources and LWC modules are 2 different sub-systems and stored differently in Salesforce. Because of the way the LWC compiler is integrated with Salesforce it is impossible to load a static resource file content in the middle of an LWC component compilation. 

Even if the compiler were resolving static resource file content during LWC module compilation it would introduce a brand new kind of technical challenges related to LWC module invalidation and re-compilation. For this reason, I don't think we will be capable to do this anytime soon on the platform.

> Also, I think it is bad for the initial loading time performance because we need to wait the JS to load, then wait the loadStyle/loadScript to be reached, and then wait the promises to be resolved. Am I right?

Correct. Loading static resources requires an extra round-trip to the server and might hurt performance in certain scenarios. I would recommend moving all the critical logic and styles inside an LWC module the extra round-trip.

**Comment by AllanOricil** [comment]
@pmdartus thanks for the clarification.

**Comment by AllanOricil** [comment]
@pmdartus sorry to bother again, but I have to ask. Why we don't need to call a method called `loadLabels` when we import a Custom Label like this `import payer from '@salesforce/label/c.payer';` ? Somehow you compile the label references, that are also stored in the platform, into the component. What would make Static Resources so different?

**Comment by pmdartus** [comment]
> What would make Static Resources so different?

The label itself doesn't have to go through the LWC compiler and is dynamically linked at runtime. At the end of the day, the label modules only export a string. On the other hand, stylesheets modules have to be compiled by the LWC compiler to be interpreted at runtime and injected into the shadow trees.

**Comment by AllanOricil** [comment]
@pmdartus I was thinking about this problem again. What if instead of bundling the assets into the components, you render the components before sending it to the client? See if it makes sense what I described in the image below:

![image](https://user-images.githubusercontent.com/55927613/135188924-4627a9e5-a76f-4674-ba4c-6011935642c8.png)

**Comment by pmdartus** [comment]
Without entering into too much detail about how modules are compiled, cached and, served at runtime in the different applications, it will be impossible to do this at Salesforce scale.
