### ISSUE TITLE
Investigate using vmBeingRendered === null vs isRendering flag

### ISSUE THREAD

**Issue by Gr8Gatsby** [salesforce/lwc#259]
_SOMA#506_

### Migrated issue

Notes:

In theory, `vmBeingRendered` should never be null when `isRendering` is true (and vise-versa). 

Questions
- Is there ever a case where `isRendering` would be false and `vmBeingRendered` would be true?
- What would be the implications of replacing `isRendering` statements with `vmBeingRendered !== null`
- It appears that TypeScript would have an easier time with `vmBeingRendered !== null`, but is that the case?

They are effectively the same. Maybe we can abstract that into a method that we use everywhere:

```js
function isRendering() {
    return vmBeingRendered !== null;
}
```

and see if engines can optimize that.

**Comment by ravijayaramappa** [comment]
This issue is obsolete now. Things have changed after PR https://github.com/salesforce/lwc/pull/1551.
The engine now has two flags, one to mark the invocation of `render()` method and another to mark the invocation of executing the template returned by the render method. In both the cases the vmBeingRendered is set. So vmBeingRendered cannot be used to infer which phase the engine is currently in.
