### ISSUE TITLE
Can't assign templates to slots?

### ISSUE THREAD

**Issue by AndrewRayCode** [salesforce/lwc#2658]
#### Steps to Reproduce

```js
<template slot="name"></template>
```

#### Expected Results
This should work

#### Actual Results
The component crashes

### Browsers Affected
All

### Version
Salesforce

**Comment by pmdartus** [comment]
In LWC template, `<template>` elements are considered as container elements should be associated with other directives like `for:each` or `if:*`. The `<template>` elements aren't actually created in the DOM. Since those elements don't have an actual DOM representation, you can't assign standard attributes including `slot`.

**Comment by AndrewRayCode** [comment]
Makes sense. This adds some friction to the development process, because:
- Now I have to think about layouting for my slot component, as in, should it be a div, or a span, or other? Which is weird since my intention is to plug into a slot, not do layouting.
- I'm not sure if LWCs see much use outside of Salesforce, and in Salesforce, they do everything they can to hinder debugging, so this use of templates crashes silently unless you're lucky enough to have a _parent_ component with an `errorCallback`, so it's not obvious what went wrong
- This generally feels like inconsistent / special-magic rules, `<template>` tags are allowed in the markup and designed to look like other tags, but they have hidden restrictions, and there's no linting / static analysis to warn you about using them "wrong". Salesforce has countless one-off issues like this, but my understanding is LWCs are supposed to be an open source framework, not coupled to Salesforce's infrastructure

Maybe I just need to learn the API better. Wanted to share my initial reaction to inconsistent template vs other tag usage

**Comment by caridy** [comment]
@AndrewRayCode this is interesting. So, you were planning to render a <template>, giving it to some other component via a slot, but it will render no content in the UI. Yes, this is perfectly fine, but my question is: what is the other component supposed to be doing with that template? is the other component LWC? That's probably were the ball drops because receiving a template element in LWC is not super useful since you can't really clone that template and dump into an LWC.

In general, I'm sympathetic with the idea of loosing the restriction of the template elements in HTML files in LWC, and treat them as regular elements. @pmdartus we might have a path forward here without breaking people.
