### ISSUE TITLE
Support for Node v18

### ISSUE THREAD

**Issue by DougMidgley** [salesforce/lwc#3217]
**Is your feature request related to a problem? Please describe.**
With Node moving to v18 LTS would be good to begin supporting this in LWR

**Describe the solution you'd like**
Update relevant dependencies to support Node v18

**Describe alternatives you've considered**
Keeping with an older LTS version. 

**Additional context**
Nope, pretty simple request here :)

**Comment by nolanlawson** [comment]
Marking this as "External: LWR" because it appears to be about LWR, not LWC. I don't believe there are any Node 18 compatibility issues with `@lwc/engine-server` or `@lwc/rollup-plugin`, but `npm init lwr` does warn because various `@lwrjs/*` packages have their supported Node versions set to `>=14.15.4 <17`.

**Comment by nolanlawson** [comment]
I just tested, and lwr works with Node 18 now. Closing!
