### ISSUE TITLE
Expand reactivity to "new-able" objects

### ISSUE THREAD

**Issue by stackasaur** [salesforce/lwc#3339]
I believe `@track` reactivity should extend to class and function instances created with `new`.

When testing the functionality, I came across a weird situation: manually setting the `__proto__` attribute on an otherwise trackable object makes it not trackable.

Consider the following code:

```
function Person(id,firstName,lastName,email){
  this.id = id;
  this.firstName = firstName
  this.lastName = lastName;
  this.email = email;
}
function getPerson(id,firstName,lastName,email){
  return {
    id,
    firstName,
    lastName,
    email
  }
}
...
this.person = getPerson('test4','Jim','Doe','test@example.com');
setTimeout(()=>{
  this.person.__proto__ = Person.prototype;
},10000);
```

Changes to `this.person` are reactive for 10 seconds, then reactivity stops being tracked. Was this a bit of a hack? Absolutely. 
But the behavior was odd.

I think lwc not allowing us to use Classes is a big missed opportunity, especially when dealing with Salesforce record data and polymorphic relationships where `instanceof` could be very useful.

-edit: [Here is an lwc.studio example showing the behavior ](https://app.lwc.studio/edit/514AiCTuFGOfOnMGZMj8/src/app.html?p=stories)

**Comment by nolanlawson** [comment]
Thanks for reporting! This might actually be an issue in [`observable-membrane`](https://github.com/salesforce/observable-membrane). /cc @caridy

**Comment by pmdartus** [comment]
Thanks for opening this issue @stackasaur.

### Short Answer

We discussed at length in the past whether LWC should track mutations on exotic objects (objects with a prototype), and we concluded that gotchas greatly outweigh the benefits. I don't think it's something we will reconsider.

----

### Long Answer

I don't think it's something we have documented anywhere else, so let me walk you through the reason why we didn't go down the path of tracking exotic objects.

As @nolanlawson mentioned, LWC uses `observable-membrane` as its reactivity system. This reactivity system tracks mutation on plain objects (objects with either a `null` prototype or `Object` prototype) and arrays. Other objects are currently ignored. This logic lives in: [`valueIsObserved`](https://github.com/salesforce/observable-membrane/blob/9c0c3eadb41c987c62a5c7a432b785b558f09105/src/observable-membrane.ts#LL31C10-L31C10).

The `observable-membrane` wraps all objects within a JavaScript `Proxy` to track property access and updates at runtime. Even if Proxies are designed to be transparent from the consumer perspective, wrapping an object within a Proxy creates an identity discontinuity. The original object identity isn't preserved when wrapped within a Proxy.

Here is an example illustrating this:

```js
const obj = { foo: true }
const proxiedObj = new Proxy(obj, {});

console.log(obj.foo);            // true
console.log(proxiedObj.foo);     // true
console.log(obj === proxiedObj); // false
```

Even if `obj` and `proxiedObj` behave similarly at runtime, they are 2 distinct objects in memory. In practice in LWC, this means that the object you set to a `@track` property is different that the one you retrieve from the same property.

```js
export default class extends LightningElement {
  @track reactive;

  connectedCallback() {
    const obj = { foo: true };
    this.reactive = obj;
    
    console.log(obj.foo);           // true
    console.log(this.reactive.foo); // true
    console.log(obj === reactive);  // false
  }
}
```

Identity discontinuity isn't a big issue when working with a simple object. In fact, I don't think that most LWC developers are aware of this. Where it becomes problematic is when you start manipulating more complex objects. By default, when invoking a method on `Proxy`, the `this` value is the proxied object and not the original object. This is problematic if the object isn't doing internally a brand check. 

Here is a concrete example illustrating this, using private fields.

```js
class Person {
  #name;

  constructor(name) {
    this.#name = name;
  }

  sayHello() {
    console.log(`Hello ${this.#name}`);
  }
}

const alex = new Person('Alex');
alex.sayHello();
```

In this example, `Person` constructor accepts a `name` argument, that is set to the `#name` private field. The private field is then used in the `sayHello()` method.

Let's take the same example, but this time let's wrap it within a `Proxy`:

```js
const alex = new Person('Alex');
const proxiedAlex = new Proxy(alex, {});
proxiedAlex.sayHello();
        // ^ Uncaught TypeError: Cannot read private member #name from an object whose class did not declare it
```

The previous example throws a `TypeError` because the `this` isn't the original object the `#name` private field is associated with. The field is associated with the original object, not the proxied one.

One might say, that a private field is a corner case and that it's ok not to support private fields on reactive objects. Unfortunately, identity check is quite common, for instance caching objects in a `Map` or a `WeakMap`. Certain JavaScript built-ins are doing similar identity checks, like `Set`.

```js
const names = new Set(['Alex', 'Nolan']);
const proxiedNames = new Proxy(names, {})

proxiedNames.has('Nolan');
// ^ Uncaught TypeError: Method Set.prototype.has called on incompatible receiver #<Set>
```
