### ISSUE TITLE
lwc:if renders out of order with for:each

### ISSUE THREAD

**Issue by stackasaur** [salesforce/lwc#3377]
### Description
When using `lwc:if` in close proximity to a `for:each`, the elements rendered to the DOM load out of order at times.

#### Steps to Reproduce

1. Loop over any iterable
2. Have a conditionally rendered block that may change after the loop
3. Add a value to the iterable and toggle the boolean controlling the `lwc:if`

```
<template for:each={items} for:item="item">
    <div key={item.id}>
        {item.text}
    </div>
</template>
<template lwc:if={items.length}>
    test
</template>
<button onclick={addItem}>add</button>


// JS
counter = 0;
addItem(){
  this.items.push(`${this.counter++}`);
}
```

If you click the button 3 times, you'd expect this to be rendered:

> 0
> 1
> 2
> test

however, you see this instead

> 0
> test
> 1
> 2

[Link to Example](https://stackblitz.com/edit/salesforce-lwc-jgxmh1?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js&title=LWC%20playground)

** Edit - I haven't had time to test all of the conditions more closely, but I felt this was the most basic example I could provide

**Comment by jye-sf** [comment]
Root Cause:
A VFragment keeps the reference to its end text node as its anchor element. This is great for knowing where the fragment ends when updating the fragment itself, but not when trying to find an anchor for insertBefore.

This use case can be generalized to the use case where nodes are being inserted immediately before a VFragment node. In that situation, the diffing algorithm uses `vnode.elm` as the anchor, which in this case is the end text node of the fragment.

Still looking into possible solutions.

**Comment by jye-sf** [comment]
Specifically, for this use case, https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-core/src/framework/rendering.ts#L935 is where the diffing algorithm grabs the incorrect `before` node to use as the anchor for `mountVNodes`:

```javascript
before = isVNode(n) ? n.elm : null;
mountVNodes(newCh, parent, renderer, before, newStartIdx, newEndIdx + 1);
```

We could fix VFragment nodes so they keep a reference to both the start and end delimiters, then modify this part of the diffing algorithm to grab the start node if `isVFragment(n)`. That would fix this specific use case.

We should also consider what other implications a vnode with two anchor points should have on the diffing algo and make the appropriate changes.
