### ISSUE TITLE
Child component's getter/setter-based property of object type is not updated when mutated in a parent component despite @track is used. 

### ISSUE THREAD

**Issue by nikitakarpenkov** [salesforce/lwc#3457]
### Description
Child component's getter/setter-based property of object type is not updated when mutated in a parent component despite @track is used. 

#### Steps to Reproduce
- Create a parent component with a private property of object type annotated with @track
- Create a child component with a public getter/setter-based property annotated with @api
- Pass parent's private property to a child
- Mutate parent's property nested value in a parent component code

It works as expected when primitive type property is used or when object type property reference is updated. It also works when a regular attribute is used instead of getter/setter.

https://stackblitz.com/edit/salesforce-lwc-aghizj?file=src/modules/x/app/app.js

#### Expected Results
Property is updated in the child component

#### Actual Results
Property is not updated in the child component

### Browsers Affected
Tested on Chrome 111.0.5563.64

### Version

- Node: 16.14.2
- LWC: 2.43.0

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nolanlawson** [comment]
Thanks for filing the bug. The key issue here seems to be this part:

```js
export default class Child extends LightningElement {
  @track
  _record; 

  @api
  apiProp;
  
  get record() {
    return this._record;
  }
  
  @api
  set record(value) {
    this._record = { ...value };
  }
}
```

If you remove the `...` spread in the `set record`, i.e.:

```diff
-this._record = { ...value };
+this._record = value;
```

... then your example works the same for both `apiProp` and `record`. So it's something about the spread / creating a new object that seems to be causing the distinction.

**Comment by nolanlawson** [comment]
OK actually I think I understand why this is happening.

In the code that _doesn't_ work, in the parent, you're doing:

```js
this.record.name = 'Foo Bar ' + Date.now();
```

The reason this doesn't work is because, when you mutate the `name` on the `record`, LWC is not updating the `record` passed down to the child. In other words, it's not calling the `set record` on the child (which makes sense – the `record` itself was not updated, only a property of the `record`).

Your code works when doing `this._record = value;` in the child setter (as opposed to `this._record = { ...value }`), because then the record object is exactly the same between the parent and the child. So mutating the parent's `record` also mutates the child's `record`.

This is also why it works for `apiProp` – the object is the same in both the parent and the child – it's equivalent to `this._record = value;`.

Whereas in the parent, when you do:

```js
this.record = { ...this.record, name: 'Foo Bar ' + Date.now() };
```

This version works in all cases because you're creating a brand-new object, which always gets passed down to the child.

After investigation, I don't think this is a bug – I think this is just how reactivity / parent-child prop-passing works in LWC. I can't see any explicit action on the side of the LWC team that would make sense here. Please let me know if I misdiagnosed the issue though. Thank you!

**Comment by nikitakarpenkov** [comment]
Thank you for looking into this issue, @nolanlawson! It's helpful to understand that the LWC parent-child reactivity implementation detects property changes by reference only and will not trigger a child component re-render when a passed property is mutated (even if it's annotated with `@track`). This makes sense, but it might be beneficial to include this information in the documentation. Instances where making a copy of an object attribute passed from a parent is necessary for mutability could be quite common.
