### ISSUE TITLE
ISNEW( )'s behavior 

### ISSUE THREAD

**Issue by SaurabhMulay999** [salesforce/lwc#3578]
This issue may not be an issue but still I though of adding it as a Feature request.

ISNEW( ) is provided to check the record is new or not.

ISSUE:
I have used the function in Validation Rule and it ain't work as well as on Formula field we ain't have access to ISNEW( ) function. I don't know whether it's an expected behavior or not but when I have refer 'LastModifiedDate!=CreatedDate' then it works well. I have checked on Internet but have not found a logical resolution on the above point.

**Comment by nolanlawson** [comment]
Thanks for opening the issue. [`ISNEW`](https://help.salesforce.com/s/articleView?id=sf.customize_functions_isnew.htm&type=5) appears to be a part of Formulas, and not the LWC open-source project (this repo).

I'd recommend posting on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) or opening a [Salesforce case](https://help.salesforce.com/s/), since there is nothing we can do in the LWC open-source project about this. Let me know if that helps.

**Comment by SaurabhMulay999** [comment]
No problem @nolanlawson I'll post it on Salesforce Stack Exchange.
