### ISSUE TITLE
Label issues with package names

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#3755]
Could you create a label for each one of the packages and add them on the issues when you already have a possible solution in mind? This could help people to quickly determine which packages they have to change in order to start/finish the task. You don't need to add all packages you think the issue relates to, just the more important ones. The engineer can figure out the rest himself.

**Comment by nolanlawson** [comment]
I appreciate the enthusiasm! 🙂 Would this also be solved by having a dedicated channel (Discord, Slack, etc.) to communicate between the LWC core team and external contributors?

I ask because going back and tagging all issues would be quite a bit of work for us, and it isn't always clear which part of the code needs to be touched to solve a particular issue.

**Comment by AllanOricil** [comment]
Well, you can do it for the new issues only. This way people can start digging the code without bothering you. 

A discord channel would also help because it can speed up communication. But I don't see it as something that will help you not being bothered in a initial analysis by the engineer.

**Comment by nolanlawson** [comment]
Being "bothered" is fine; this is normal for onboarding new OSS contributors. 😄

**Comment by AllanOricil** [comment]
@nolanlawson you could add a clickalbe badge pointing to the discussion channel when you launch it

<img width="114" alt="image" src="https://github.com/salesforce/lwc/assets/55927613/3fbc064e-aa9f-4e22-a61f-826a559d434a">

ref: https://github.com/oven-sh/bun
