### ISSUE TITLE
Maintaining the Id Attributes after component render.

### ISSUE THREAD

**Issue by SourabhMulay** [salesforce/lwc#4414]
Ref to: https://github.com/salesforce/lwc/issues/1969

In an automation test script, fetching a DOM node using its attribute ID failed because the ID was modified to a global value at runtime. As a result, the initial ID value differs once the component has rendered in the DOM.

isn't this change impact the effectiveness of automation scripts and fully automated testing tools??  even though optimisations in the test scripts are possible.

**Comment by nolanlawson** [comment]
Thanks for reporting. The `id` mangling (e.g. `id="foo"` becomes `id-"foo-0"`) only occurs in synthetic shadow DOM, to simulate ID-scoping in native shadow DOM.

We do not intend to change this behavior in synthetic shadow DOM, because synthetic shadow DOM is legacy (maintenance mode). To disable the ID mangling, you can use [native shadow DOM](https://developer.salesforce.com/blogs/2024/01/get-your-lwc-components-ready-native-shadow-dom) which is GA.

Please let me know if this resolves your question.

**Comment by SourabhMulay** [comment]
Thanks for the confirmation @nolanlawson !!!
